## Numpy

## Numpy
1. Create array  (Effects of mixed types,from a list or series)
2. Subset
3. EDA
4. Parse array in for loop
5. Reverse Index
6. Multi Dimensional Array Subset
7. Random Values
8. Get max
9. Get index with main value
10. Create nan value in element
11. Check type of array
12. Check within values are nan


In [2]:
import numpy as np
import pandas as pd

In [5]:
n1 = np.array([1,2,3])
n1

array([1, 2, 3])

In [7]:
l1 = [1,2,3,4]
n2  =np.array(l1)
n1

array([1, 2, 3])

In [9]:
t=(1,2,3)
n3 = np.array(t)
n3

array([1, 2, 3])

In [14]:
s ='hello'
l=[]
for i in s:
    l.append(i)
s1=np.array(l)
s1


array(['h', 'e', 'l', 'l', 'o'], dtype='<U1')

In [17]:
l2=[5,6,7,8]

In [20]:
n3=np.array([l1,l2])

In [21]:
n3.ndim

2

In [22]:
n3.shape

(2, 4)

In [23]:
n1.ndim

1

In [24]:
n1

array([1, 2, 3])

In [26]:
n3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
n5 = [[[1,2,3],[2,3,4],[5,6,7]],[[1,2,3],[2,3,4],[5,6,7]]]

In [35]:
np.array(n5)

array([[[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]],

       [[1, 2, 3],
        [2, 3, 4],
        [5, 6, 7]]])

In [36]:
np.array([1,'Hello',True])

array(['1', 'Hello', 'True'], dtype='<U11')

In [38]:
pd.Series(l1)

0    1
1    2
2    3
3    4
dtype: int64

In [39]:
pd.Series([1,2,3,4,5,6,7])

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [40]:
pd.Series(n1)

0    1
1    2
2    3
dtype: int32

In [42]:
n3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
n3.ndim

2

In [47]:
n2

array([1, 2, 3, 4])

In [46]:
n2[1]

2

In [48]:
n2[0:2]

array([1, 2])

In [61]:
nr = np.arange(0,20)

In [62]:
nr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
nr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
nr[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [65]:
pdx=pd.Series(nr)

In [66]:
pdx

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int32

In [67]:
pdx[5]

5

In [69]:
pdx[::2]

0      0
2      2
4      4
6      6
8      8
10    10
12    12
14    14
16    16
18    18
dtype: int32

In [71]:
pdx[1::2]

1      1
3      3
5      5
7      7
9      9
11    11
13    13
15    15
17    17
19    19
dtype: int32

In [94]:
pdx.sort_values()

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int32

In [74]:
nr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
for i in nr:
    if i%3==0:
        print(i)
    else:
        continue

0
3
6
9
12
15
18


In [79]:
nr.mean()

9.5

In [81]:
nr.sum()

190

In [84]:
np.median(nr)

9.5

In [90]:
pdx.mean()

9.5

In [92]:
pdx.median()

9.5

In [93]:
pdx.mode()

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int32

In [98]:
np.sort(nr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [99]:
n3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
n3[0]

array([1, 2, 3, 4])

In [102]:
n3[1]

array([5, 6, 7, 8])

In [103]:
n3[0][2]

3

In [117]:
import random
np.random.seed(42)


In [118]:
n1= np.random.randint(5,15,10)

In [123]:
n1

array([11,  8, 12,  9, 11, 14,  7, 11, 12,  9])

In [124]:
n1

array([11,  8, 12,  9, 11, 14,  7, 11, 12,  9])

In [134]:
nr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [135]:
nr[3] =11

In [136]:
nr

array([ 0,  1,  2, 11,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [141]:
ns=np.insert(nr,2,55,axis=0)

In [142]:
ns

array([ 0,  1, 55,  2, 11,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19])

In [143]:
np.append(nr,n2,axis=0)

array([ 0,  1,  2, 11,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  1,  2,  3,  4])

In [147]:
np.append(n1,l1,axis=0)

array([11,  8, 12,  9, 11, 14,  7, 11, 12,  9,  1,  2,  3,  4])

In [148]:
n1

array([11,  8, 12,  9, 11, 14,  7, 11, 12,  9])

In [152]:
na = np.arange(0,10,3)

In [153]:
l1

[1, 2, 3, 4]

In [160]:
na=np.append(na,l1,axis=0)

In [158]:
np.append(na,na,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [161]:
na

array([0, 3, 6, 9, 1, 2, 3, 4])

In [162]:
nr.max()

19

In [163]:
nr.argmax()

19

In [164]:
nr

array([ 0,  1,  2, 11,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [166]:
na.max()

9

In [167]:
na.argmax()

3

In [168]:
na

array([0, 3, 6, 9, 1, 2, 3, 4])

In [169]:
na.min()

0

In [170]:
na.argmin()

0

In [171]:
np.delete(nr,2,axis=0)

array([ 0,  1, 11,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [176]:
nx = np.array([1.2,1.8,55.66])

In [183]:
nx=np.insert(nx,2,np.nan,axis=0)

In [178]:
type(nx)

numpy.ndarray

In [184]:
np.isnan(nx)

array([False, False,  True, False])

## Pandas

In [46]:
import pandas as pd
#Creation of Df

lx=['A','B','C']

In [50]:
df1 = pd.DataFrame([[1,2,3],[4,5,6]],columns=lx,index=lx[0:2])

In [9]:
df2 = pd.DataFrame([[1,2,3],[4,5,6]])

In [51]:
df1

A  B  C
A  1  2  3
B  4  5  6

In [10]:
df2

0  1  2
0  1  2  3
1  4  5  6

In [42]:
l1 = ['A','B','C','D']
l2 = [1,2,3,4,5]
d = list(zip(l1,l2))
d

[('A', 1), ('B', 2), ('C', 3), ('D', 4)]

In [44]:
df3 = pd.DataFrame(d)
df3

0  1
0  A  1
1  B  2
2  C  3
3  D  4

In [52]:
df1.index

Index(['A', 'B'], dtype='object')

In [53]:
)

index  A  B  C
0     A  1  2  3
1     B  4  5  6

In [86]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [23, 35, 45, 28, 22],
    'Gender': ['F', 'M', 'M', 'M', 'F'],
    'Score': [85, 90, 88, 95, 70],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

# Creating DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df

Name  Age Gender  Score         City
0    Alice   23      F     85     New York
1      Bob   35      M     90  Los Angeles
2  Charlie   45      M     88      Chicago
3    David   28      M     95      Houston
4      Eva   22      F     70      Phoenix

In [56]:
df.set_index()

index     Name  Age Gender  Score         City
0      0    Alice   23      F     85     New York
1      1      Bob   35      M     90  Los Angeles
2      2  Charlie   45      M     88      Chicago
3      3    David   28      M     95      Houston
4      4      Eva   22      F     70      Phoenix

In [102]:
df.loc[df['Name']=='Bob','Age']=30

In [103]:
df

Name  Age Gender  Score         City
0    Alice   23      F     85     New York
1      Bob   30      M     90  Los Angeles
2  Charlie   45      M     88      Chicago
3    David   28      M     95      Houston
4      Eva   22      F     70      Phoenix

In [78]:
df

Name  Age Gender  Score         City
0    Alice   23      F     85     New York
1      Bob   35      M     90  Los Angeles
2  Charlie   45      M     88      Chicago
3    David   28      M     95      Houston
4      Eva   22      F     70      Phoenix

In [85]:
df

35

Marks for P is 10
Marks for R is 26


Marks for P is 10
Marks for R is 26
