In [1]:
import numpy as np

In [5]:
#1 create array with numbers 0,1,2,..10
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#2 create array with numbers -10,-9,...0
np.arange(-10,1)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [9]:
#3 create array with all even numbers in 0 to 100
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [11]:
#4 take array in Q1 and reverse it
Q1 = np.arange(1,16).reshape(5,3)


print(Q1[::-1])


[[13 14 15]
 [10 11 12]
 [ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]]


In [1]:
#5 create array with perfect square numbers in 0 to 100 (e.g. 9 is one because it is square of 3)
squares = []
i = 0
while i**2 <= 100:
    squares.append(i**2)
    i += 1

print(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [3]:
#6 create an unsorted array, sort it in ascending order
np.random.seed(22)
n1 = np.random.randint(0,100,10)
#n1 = np.sort(n1)
n1.sort()
n1

array([ 4,  8, 14, 18, 44, 45, 64, 84, 93, 95])

In [15]:
#7 create an unsorted array, sort it in descending order
np.random.seed(22)
n2 = np.random.randint(0,100,10)
#Method1 = 
n2 = -np.sort(-n2)
#n2 = np.sort(n2)[::-1]
n2

array([95, 93, 84, 64, 45, 44, 18, 14,  8,  4])

In [81]:
#8 take an array, find out unique values in it
n3 = np.array([11,3,22,56,44,11,22,66,44])
n4 = np.unique(n3)
n4

array([ 3, 11, 22, 44, 56, 66])

In [28]:
#9 solve question 1 from mid term. Take two 3x2 matrices ...

In [93]:
#10 create a function which accepts a value and returns its square and cube as a tuple
def sq_cub_tup(num):
    return num**2,num**3

In [95]:
f1 = sq_cub_tup(3)
print(f1)
print(type(f1))

(9, 27)
<class 'tuple'>


In [101]:
#11 modify the function to return a list
def sq_cub_lst(num):
    return [num**2,num**3]

In [103]:
f2 = sq_cub_lst(3)
print(f2)
print(type(f2))

[9, 27]
<class 'list'>


In [11]:
#12 modify the function to return an array
def sq_cub_arr(num):
    n1 =  np.array([num**2,num**3])
    print(n1.shape())
    return n1

In [39]:
#13 Given y = 4 * (x**3) - 0.5*(x**2) + 7*x - 4
# create a function to return square of a given number. another function to create cube of a given number. 
# use these functions to calculate y given a number

In [111]:
def sqr(num):
    return num**2
def cub(num):
    return num**3
x = 7
y = 4 * (cub(x)) - 0.5 * sqr(x) + 7*x - 4
print(y)


1392.5


In [144]:
#14 create a function which calculates factorial of a given number
def factorial(n):
    fact = 1
    l=[]
    for i in range(1,n+1):
        fact = fact*i
        l.append(fact)
    print(np.array(l))
    return fact

In [146]:
factorial(5)

[  1   2   6  24 120]


120

In [156]:
#15 generate two arrays:
mat1 = np.random.randint(1,20,5)
mat2 = np.random.randint(0,25,5)
cov = np.cov(mat1,mat2)
corr = np.correlate(mat1,mat2)
print('Covarience is',cov)
print('Correlation is',corr)
#calculate their covariance and correlation using numpy methods
#calculate from scratch and compare values.

Covarience is [[41.5  36.75]
 [36.75 64.3 ]]
Correlation is [831]


In [154]:
#16 generate a 5 x 3 matrix and calculate covariance using numpy .cov. 
# For one element in the principal diagonal and one other element calculate from scratch and compare values.

In [170]:
#17 create a 3x3 matrix, get its inverse. Verify if numpy calculated the inverse correctly.
mat3 = np.random.randint(1,20,9).reshape(3,3)
print('The marix is:', mat3)
inv = np.linalg.inv(mat3)
print('The inverse is:',inv)

The marix is: [[ 6  7 11]
 [ 7 13  5]
 [12  9  2]]
The inverse is: [[ 0.02331288 -0.10429448  0.13251534]
 [-0.05644172  0.14723926 -0.05766871]
 [ 0.11411043 -0.03680982 -0.03558282]]


In [186]:
mat4 = np.array([[ 1,2,3],[ 3,6,9],[-2,-4,-6]])
print(np.linalg.det(mat4))                      #Determinant is zero

0.0


In [188]:
#18 in a matrix if one row is a scalar product of another row then it cannot be inverted. take an example and verify.

inv1 = np.linalg.inv(mat4)
inv1

LinAlgError: Singular matrix

In [21]:
#19 Create a square matrix A, A.I is its inverse. A.T is its tranpose. Find out the relationship between A.T.I and A.I.
# A is non singular, i.e. it is invertible.
np.random.seed(44)
A = np.random.randint(0,10,9).reshape(3,3)
I = np.eye(3)
if np.linalg.det(A) !=0:
    inv = np.linalg.inv(A)
    AI = np.dot(A,I)
    tran = np.transpose(A)

else:
    print('Det is zero')

print('Inverse is: ',inv)
print('AI is:',AI)
print('transpose is:',tran)




Inverse is:  [[ 0.24427481  0.09923664 -0.09160305]
 [ 0.06870229 -0.19083969  0.09923664]
 [-0.18320611  0.17557252  0.06870229]]
AI is: [[4. 3. 1.]
 [3. 0. 4.]
 [3. 8. 7.]]
transpose is: [[4 3 3]
 [3 0 8]
 [1 4 7]]


In [23]:
#(AT)T = A
print("Checking Transpose Law")
tt = np.transpose(tran)
print('Transposed to Transposed Array is:',tt)
print('Original Array is:',A)

Checking Transpose Law
Transposed to Transposed Array is: [[4 3 1]
 [3 0 4]
 [3 8 7]]
Original Array is: [[4 3 1]
 [3 0 4]
 [3 8 7]]


In [31]:
if tt.all() == A.all():
    print('tran == A')
else:
    print('No')                            #Why this not working

tran == A


In [222]:
#20 consider a 5 x 3 matrix. Let its columns be C1,C2 and C3.Can you switch them to it is now C2,C3 and C1?
mat5 = np.random.randint(2,50,15).reshape(5,3)
print('Original Matrix:',mat5)
mat6 = np.roll(mat5,2,axis=1)
print('Swapped Columns:',mat6)

Original Matrix: [[30 31  3]
 [14  4 13]
 [47  4 11]
 [10 43 38]
 [36 12  8]]
Swapped Columns: [[31  3 30]
 [ 4 13 14]
 [ 4 11 47]
 [43 38 10]
 [12  8 36]]


In [37]:
#21 take an array of 10 elements, count the number of positive values
np.random.seed(44)
mat7=np.random.randint(-5,10,10)
print('The matrix is:',mat7)
pos = 0
neg = 0
zero = 0
for i in mat7:
    if i>0:
        pos = pos+1
    elif i<0:
        neg = neg+1
    else:
        zero = zero+1
print('Total Positive numbers are:',pos)
print('Total negative numbers are:',neg)
print('Total zeros are:',zero)
        

The matrix is: [-1 -2 -4  8  6 -2 -5 -1 -2  5]
Total Positive numbers are: 3
Total negative numbers are: 7
Total zeros are: 0


In [236]:
np.sum(mat7>0)  

3

In [246]:
len(mat7[mat7>0])

3

In [43]:
#22 take a matrix of 5x5, count the positive values.
np.random.seed(44)
mat8=np.random.randint(-20,20,25).reshape(5,5)
print('The matrix is:',mat7)
pos = 0
neg = 0
zero = 0
for i,j in range(mat7):
    if mat7[i,j]>0:
        pos = pos+1
    elif mat7[i,j]<0:
        neg = neg+1
    else:
        zero = zero+1
print('Total Positive numbers are:',pos)
print('Total negative numbers are:',neg)
print('Total zeros are:',zero)

The matrix is: [-1 -2 -4  8  6 -2 -5 -1 -2  5]


TypeError: only integer scalar arrays can be converted to a scalar index

In [242]:
np.random.seed(44)
mat8=np.random.randint(-20,20,25).reshape(5,5)
len(mat8[mat8>0])

14

In [244]:
np.sum(mat8>0)

14

## IMP

In [256]:
#23 create two vectors of 5 dimensions, u and v. 
# calculate their norms
# calculate their dotproduct
# calculate the angle between them in degrees
u = np.array([1, 2, 3, 4, 5])
v = np.array([5, 4, 3, 2, 1])
normu = np.linalg.norm(u)
normv = np.linalg.norm(v)
dp = np.dot(u, v)

cos_theta = dp/ (normu * normv)
angle_radians = np.arccos(np.clip(cos_theta, -1.0, 1.0))
angle_degrees = np.degrees(angle_radians)
print("Vector u:", u)
print("Vector v:", v)
print("Norm of u:", normu)
print("Norm of v:", normv)
print("Dot product of u and v:", dp)
print("Angle between u and v (degrees):", angle_degrees)


Vector u: [1 2 3 4 5]
Vector v: [5 4 3 2 1]
Norm of u: 7.416198487095663
Norm of v: 7.416198487095663
Dot product of u and v: 35
Angle between u and v (degrees): 50.47880364135783
