


- Which plot to use for each Category  -> 1 Num    -> N-N  ->C-N  ->C-C   ->c-c-n

## OOPS

1. Class 
    1. Create empty
    2. Create with method
    3. Create with constructor
    4. Create with Class Variable
2. Object
    1. Create instance of a class
    2. Call methods
    3. Modify instance Variable
    4. add instance variable.
3. Class
    1. Inherit from parent class.
    2. Variable types
    3. Demonstrate basic concept using example.

In [18]:
import numpy as np
import pandas as pd

In [2]:
a1 = np.arange(10,20)

In [8]:
a1=a1.reshape(5,2)

In [9]:
a1

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [16]:
def parse_val(n,i):
    for i in n.shape:
        return n[0:i]


In [17]:
parse_val(a1,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [20]:
ep=pd.Series()

In [21]:
ep

Series([], dtype: object)

In [27]:
ep1 = pd.Series([1,2,3,4,5,6,8,7])

In [28]:
ep1

0    1
1    2
2    3
3    4
4    5
5    6
6    8
7    7
dtype: int64

In [29]:
ep1.iloc[1]

np.int64(2)

In [33]:
ep1[1]
len(ep1)

8

In [35]:
for i,j in ep1.items():
    print('Index is ',i)
    print('The Value is: ',j)
    

Index is  0
The Value is:  1
Index is  1
The Value is:  2
Index is  2
The Value is:  3
Index is  3
The Value is:  4
Index is  4
The Value is:  5
Index is  5
The Value is:  6
Index is  6
The Value is:  8
Index is  7
The Value is:  7


In [37]:
n1 = np.arange(1,5)
n1

array([1, 2, 3, 4])

In [38]:
s1 = pd.Series(n1)

In [39]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [52]:
l1 = [1,2,3,4,10,4]
s2 = pd.Series(l1)

In [53]:
s2

0     1
1     2
2     3
3     4
4    10
5     4
dtype: int64

In [54]:
s2.mean()

np.float64(4.0)

In [55]:
s2.median()

np.float64(3.5)

In [56]:
s2.mode()

0    4
dtype: int64

In [57]:
s2

0     1
1     2
2     3
3     4
4    10
5     4
dtype: int64

In [58]:
k = [1,2,3,4]
v = [22,33,44]
d = {}
for i in zip(k,v):
    d.keys=

(1, 22)
(2, 33)
(3, 44)


In [65]:
# Write a program that accepts a string and calculates the number of digits and letters



def sum_nd(s):
    if '.' in s:
        s1 = s.split('.')
        return s1
    else:
        return s
    

In [66]:
sum_nd('2.5')

['2', '5']

In [80]:
a = 'python 3.2'
l = []
lat = []
a  =[0,1,2,3,4,5,6,7,8,9]
for i in a:
    if i in str(a):
        l.append(i)
    elif i not in str(a):
        lat.append(i)
        
    else:
        continue
        
print(f'Letters are: {len(lat)} and Digits are {len(l)}')
print(lat)
        


TypeError: 'in <string>' requires string as left operand, not int

In [86]:
a = 'python 3.2'
l = []
lat = []
lx = [0,1,2,3,4,5,6,7,8,9]
for j in a:
    if j in str(lx):
        l.append(j)
    else:
        lat.append(j)
            

        
        
print(f'Letters are: {len(lat)} and Digits are {len(l)}')
print(lat)
print(l)

Letters are: 7 and Digits are 3
['p', 'y', 't', 'h', 'o', 'n', '.']
[' ', '3', '2']


In [79]:
a  =range(0,10)
a

range(0, 10)

In [69]:
def lat_dig(a):
    l = []
    lat = []
    for i in range(0,10):
        if str(i) in a:
            l.append(i)
        else:
            lat.append(i)
        
        
    return f'Letters are: {lat} and Digits are {l}'